### ISSUE TITLE
scGPT model

### ISSUE THREAD

**Issue by rcannood** [openproblems-bio/task_batch_integration#14]
Is this model available on something like huggingface or zenodo?

https://github.com/openproblems-bio/task_batch_integration/blob/52ccedbd0221be2af27c3e9dd584a7ae63e8a0a1/src/methods/scgpt/script.py#L47-L51

If not, can we move this to our s3 bucket? If the google drive is removed this component would no longer work.

**Comment by lazappi** [comment]
No, it's only on Google Drive (at least officially) but I can move it.

**Comment by HelloWorldLTY** [comment]
Hi, I am interested in adding scFoundation (and/or) CellPLM in this benchmark. What do you think? Thanks a lot.

Also, I am not sure if it is feasible to upload pre-trained weights to huggingface or zendo, will it be conflcit with some patents?

**Comment by lazappi** [comment]
> Hi, I am interested in adding scFoundation (and/or) CellPLM in this benchmark. What do you think? Thanks a lot.

That would be great! Can you please open a separate issue(s) to discuss?

> Also, I am not sure if it is feasible to upload pre-trained weights to huggingface or zendo, will it be conflcit with some patents?

I'm not sure if there are restrictions but some other foundation models host the pre-trained weights on huggingface or zenodo.

**Comment by HelloWorldLTY** [comment]
I think some models like scFoundation might have their own liscences for model weights, but I will figure it out. Thanks.
